# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    # About: /about/index.html

# Customize
customize:
    logo:
        width: 165
        height: 60
        url: images/logo-header.png
    theme_color: '#2db9b9'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: favicon.ico # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        github: https://github.com/zirho

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: zirhocodepaste # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    scrollLoading: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
